### ISSUE TITLE
Reindexing to-do list

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3601]
Things to begin indexing:
- [ ] Author ORCIDs
- [ ] Funder Award IDs
- [ ] Funder ROR IDs
- [ ] Sponsor ROR IDs

Aliasing:

- [x] Not sure if it requires reindexing or something else (aliasing?), but Journals should be searchable by ISSN as well as name.
- [ ] Similarly for funders and affiliations, whose names can change a lot, it would seem better to index the ROR IDs and use the names as aliases for those, rather than search the names alone (and have to do some kind of historical cleanup whenever they change)
