### ISSUE TITLE
Submission system redesign - existing functionality checklist

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3713]
- [x] Edit submission
- [x] Preview submission
- [x] Error checks
- [x] Collections
- [x] Highlights for curators
- [x] Changes made check
- [x] Curators hide readme
- [x] Describe edits
- [x] Duplicate check
- [x] Select licenses for zenodo files (do #2707 first)
- [x] File edit note
- [x] 'Editing another user's dataset' 
- [x] Checks for automatic PPR/No PPR allowed
