### ISSUE TITLE
EPIC: GREI connecting digital objects

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3778]
1. PubUpdater
  - [x] [Clear the backlog](https://trello.com/c/kCF6hEGZ)
  - [x] [Document the process](https://trello.com/c/TdHWM99x)
  - [x] Automated reminders https://github.com/datadryad/dryad-product-roadmap/issues/2609 https://github.com/datadryad/dryad-product-roadmap/issues/2754#issue-1871809949 
  - [ ] https://github.com/datadryad/dryad-product-roadmap/issues/3344 https://trello.com/c/LMf4s7Lv
2. CEDAR
  - [x] [Publish additional neural imaging data](https://trello.com/c/GsKz0LUM) (on hold)
  - [ ] [Engage relevant disciplinary repository in conversation](https://trello.com/c/v6QqYrB2)
  - [ ] [Recruit an additional research group](https://trello.com/c/KdEhyVP0)
3. Advocate for PIDs
  - https://github.com/datadryad/dryad-product-roadmap/issues/2516
  - [ ] [Host a webinar](Sarah presenting at Datacite webinar on ROR and Dryad) 
  - [x] [Attend PIDfest](https://trello.com/c/TON6SICi) 
4. FOS vs FOR
  - [x] [Situation review](https://trello.com/c/0gOCe5gr)
  - [x] https://github.com/datadryad/dryad-product-roadmap/issues/3765 [Decision](https://trello.com/c/JvgiWzSN)
5. Share community initiatives with CWG
 - [Data availability statements](https://trello.com/c/iYL7pLWA)
 - https://github.com/datadryad/dryad-product-roadmap/issues/3766 [Traditional knowledge labels](https://trello.com/c/8DycJk5j)
 - https://github.com/datadryad/dryad-product-roadmap/issues/3403 [Indicating retractions](https://trello.com/c/7cJ71h5V)

**Comment by ryscher** [comment]
Closing, since this describes GREI Year 3 work that has been completed or reconfigured into Year 4.
