### ISSUE TITLE
EPIC: GREI QA/QC

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3780]
Dryad internal:
1. [ ] [README automation](https://trello.com/c/KJ4UR14N) https://github.com/datadryad/dryad-product-roadmap/issues/3531 https://github.com/datadryad/dryad-product-roadmap/issues/3779
2. [x] [Pull metadata from data files and articles](https://trello.com/c/GK009z4z) (will revisit in in-person meeting) 
3. https://github.com/datadryad/dryad-product-roadmap/issues/2435
4. https://github.com/datadryad/dryad-product-roadmap/issues/3410
5. https://github.com/datadryad/dryad-product-roadmap/issues/3814
6. [x] [Issues with specific file types](https://trello.com/c/Y08H3wQM)
7. [x] [Free curator time](https://trello.com/c/mxgvvpWy) (ongoing improvements as needed)
8. [x] [Automated email chases](https://trello.com/c/cH9hOqPB)

GREI task group:
- https://github.com/datadryad/dryad-product-roadmap/issues/3683
- https://github.com/NIH-GREI/grei-pm/issues/134

**Comment by ryscher** [comment]
Closing, since this described Year 3 GREI owkr that has either been completed or reconfigurednin Year 4.
